# =============================================================================
# Terraform Outputs
# =============================================================================
# These outputs provide values needed to configure the backend application.
# Sensitive values (like API keys) should be retrieved from Azure Portal or CLI.
# =============================================================================

# -----------------------------------------------------------------------------
# Resource Group
# -----------------------------------------------------------------------------
output "resource_group_name" {
  description = "Name of the resource group"
  value       = azurerm_resource_group.main.name
}

output "resource_group_location" {
  description = "Location of the resource group"
  value       = azurerm_resource_group.main.location
}

# -----------------------------------------------------------------------------
# Azure OpenAI Service
# -----------------------------------------------------------------------------
output "openai_endpoint" {
  description = "Azure OpenAI endpoint URL"
  value       = azurerm_cognitive_account.openai.endpoint
}

output "openai_account_name" {
  description = "Azure OpenAI account name"
  value       = azurerm_cognitive_account.openai.name
}

output "openai_resource_id" {
  description = "Azure OpenAI resource ID"
  value       = azurerm_cognitive_account.openai.id
}

# -----------------------------------------------------------------------------
# Model Deployments
# -----------------------------------------------------------------------------
output "embedding_deployment_name" {
  description = "Name of the embedding model deployment"
  value       = azurerm_cognitive_deployment.embedding.name
}

output "llm_deployment_name" {
  description = "Name of the LLM model deployment"
  value       = azurerm_cognitive_deployment.llm.name
}

# -----------------------------------------------------------------------------
# Connection Information (for .env file)
# -----------------------------------------------------------------------------
output "backend_env_config" {
  description = "Environment variables to add to backend .env file"
  value       = <<-EOT
    # Azure OpenAI Configuration (generated by Terraform)
    AZURE_OPENAI_ENDPOINT=${azurerm_cognitive_account.openai.endpoint}
    AZURE_OPENAI_EMBEDDING_DEPLOYMENT=${azurerm_cognitive_deployment.embedding.name}
    AZURE_OPENAI_LLM_DEPLOYMENT=${azurerm_cognitive_deployment.llm.name}
    AZURE_OPENAI_API_VERSION=2024-02-15-preview

    # IMPORTANT: Get API key manually using:
    # az cognitiveservices account keys list --name ${azurerm_cognitive_account.openai.name} --resource-group ${azurerm_resource_group.main.name} --query "key1" -o tsv
    AZURE_OPENAI_API_KEY=<retrieve-from-azure>
  EOT
}

# -----------------------------------------------------------------------------
# CLI Commands for API Key Retrieval
# -----------------------------------------------------------------------------
output "api_key_command" {
  description = "Azure CLI command to retrieve the API key"
  value       = "az cognitiveservices account keys list --name ${azurerm_cognitive_account.openai.name} --resource-group ${azurerm_resource_group.main.name} --query \"key1\" -o tsv"
}

# -----------------------------------------------------------------------------
# Budget Information
# -----------------------------------------------------------------------------
output "budget_name" {
  description = "Name of the budget alert"
  value       = azurerm_consumption_budget_resource_group.main.name
}

output "budget_amount" {
  description = "Monthly budget amount in USD"
  value       = var.budget_amount
}
